add page objects, step file and methods to extensions
NikitaGavruk/AT-LAB-2023-CW-39 pull request #12
Opened 2023-07-31 09:12 UTC by evgkas

2023-07-31 09:31 UTC, sirojbekdev approved these changes

2023-07-31 10:19 UTC, khayitmuradov approved these changes

2023-07-31 18:55 UTC, NikitaGavruk requested changes

2023-07-31 18:55 UTC, NikitaGavruk commented on UI/Pages/ArticlePage.cs
> +        public static readonly By editButton = By.CssSelector("#ca-edit>a>span");
Please make all By private. We need them only in pages

2023-07-31 18:55 UTC, NikitaGavruk commented on UI/Steps/Steps.cs
> +        public static void Login(string username, string password, int timeSeconds)
Please create two files:
1. LoginPageSteps which will contain Login function
2. MainPageSteps which will contan Logout and Search functions

2023-07-31 18:55 UTC, NikitaGavruk commented on UI/Steps/Steps.cs
> +            mainPage.ClickToLogout(2);
It is better to avoid this hardcoded timeout. Just paste same timeSeconds variable. Do it in function below and above

2023-07-31 18:55 UTC, NikitaGavruk commented on UI/Pages/LoginPage.cs
> +        public void EnterUsername(string username, int timeSeconds)
Functions of pages need to return new PageName(). It is called Fluent Page Object. Read it please
https://www.lambdatest.com/blog/fluent-interface-design-pattern/

2023-07-31 18:56 UTC, NikitaGavruk commented
Despite the flaws, it looks cool. Keep it in same way

2023-08-01 10:27 UTC, NikitaGavruk approved these changes

2023-08-01 10:27 UTC, merged