Tests Yauheni
NikitaGavruk/AT-LAB-2023-CW-39 pull request #15
Opened 2023-08-01 12:42 UTC by evgkas

2023-08-01 13:02 UTC, khayitmuradov approved these changes

2023-08-01 17:05 UTC, sirojbekdev approved these changes

2023-08-01 20:13 UTC, NikitaGavruk requested changes

2023-08-01 20:13 UTC, NikitaGavruk commented on UI/Pages/LoginPage.cs
> +            WebDriverExtension.SendKeysToElement(usernameField, username);
Should return new LoginPage(). Same in functions below

2023-08-01 20:13 UTC, NikitaGavruk commented on UI/Steps/LoginPagesSteps.cs
> +            loginPage.EnterUsername(username);
As this page functions return Page then you can made it via
loginPage.EnterUsername(username).EnterPassword(password).ClickToLoginButton()
Same in functions below

2023-08-01 20:13 UTC, NikitaGavruk commented on UI/Tests/Test.cs
> +            CustomLogger.LogInfo(Utils.LogLevel.Info, "Go to Main page");
Delete it or move after login

2023-08-01 20:13 UTC, NikitaGavruk commented on UI/Tests/Test.cs
> +        private static string username = "AliceTestAcc4587";
Let's create a new xml(or another extension) file in Core project which will contain this data and name it TestsConfig.xml

2023-08-02 07:53 UTC, evgkas commented
I have added TestDataReader to read user credentials from json. This class may be extended further.

2023-08-02 12:23 UTC, NikitaGavruk commented
@evgkas please fix conflict and then merge it to main

2023-08-02 12:26 UTC, merged