FEAT: add CheckSwitchLanguage in Test.cs, create LanguagesPage.cs
NikitaGavruk/AT-LAB-2023-CW-39 pull request #21
Opened 2023-08-03 07:13 UTC by khayitmuradov

created LanguagesPage.cs in Pages folder
added CheckSwitchLanguage() method in Test.cs

2023-08-03 15:54 UTC, NikitaGavruk requested changes

2023-08-03 15:54 UTC, NikitaGavruk commented on UI/Pages/LanguagesPage.cs
> +        public void ClickPopUpWindowButton()
Make it please via fluent page object pattern

2023-08-03 15:54 UTC, NikitaGavruk commented on UI/Tests/Test.cs
> +            languagesPage.ClickUzbekLanguageButton();
Add please log info here too as you did it on 85 line

2023-08-03 15:54 UTC, NikitaGavruk commented on UI/Tests/Test.cs
> +            languagesPage.ClickUzbekWikipediaButton();
Why you did not verify Uzbek language?

2023-08-03 16:02 UTC, NikitaGavruk commented
What does it mean "FEAT" at name of this PR?

2023-08-03 16:12 UTC, khayitmuradov commented
FEAT means feature no? when I read it from that documentation about commiting which you gave

2023-08-03 21:26 UTC, khayitmuradov commented
> What does it mean "FEAT" at name of this PR?
Reworked Languages Part: #21

2023-08-04 06:16 UTC, NikitaGavruk commented
:) I did not read it. Anyway we do not need it. We just need to have clear commits name

2023-08-04 06:18 UTC, NikitaGavruk approved these changes

2023-08-04 06:19 UTC, merged