Api test Yauheni
NikitaGavruk/AT-LAB-2023-CW-39 pull request #26
Opened 2023-08-09 10:48 UTC by evgkas

Add classes to create requests. Add BaseTest. Fix path error in ExpectedDataReader and TestDataReader

2023-08-09 13:32 UTC, Abdulaziz-rgb requested changes

2023-08-09 13:32 UTC, Abdulaziz-rgb commented on API/Tests/Tests.cs
> +            string url = "https://en.wikipedia.org/api/rest_v1/page/pdf/Mikhail_Lomonosov";
I think it would be better if you use the base url part of the endpoint whenever you initialize a new singleton instance of restclient (I mean in Client class)

2023-08-09 13:32 UTC, Abdulaziz-rgb commented on Core/resources/expectedData.json
> +  "expected_content_type": "application/pdf"
I do not know whether I am right but I think we had better work with separate json file  in API Project.

2023-08-09 13:32 UTC, Abdulaziz-rgb commented on API/APIUtils/API.cs
> +
remove blank line

2023-08-09 13:32 UTC, Abdulaziz-rgb commented on API/APIUtils/API.cs
> +            return request;
Leave a blank line before return statement

2023-08-10 14:36 UTC, evgkas commented
Separate API and UI test Data and change the way of getting data: now there is no need to add method in the model for every line. Reading of all Data is realized in TestDataReader

2023-08-11 07:33 UTC, NikitaGavruk commented
Fix merge conflict and I will merge

2023-08-11 08:17 UTC, evgkas commented
> Fix merge conflict and I will merge

Done

2023-08-11 09:07 UTC, merged