update Browser.GetDriver() and other methods
NikitaGavruk/AT-LAB-2023-CW-39 pull request #9
Opened 2023-07-28 12:39 UTC by evgkas

update to protect from null reference exception

2023-07-28 16:46 UTC, khayitmuradov approved these changes

2023-07-28 19:48 UTC, NikitaGavruk requested changes

2023-07-28 19:48 UTC, NikitaGavruk commented on UI/WebDriver/Browser.cs
> +            GetDriver().Manage().Window.Maximize();
Please move them via "Tab" or "Space" to achieve evenness

2023-07-28 19:48 UTC, NikitaGavruk commented on UI/WebDriver/Browser.cs
> +            GetDriver().Navigate().GoToUrl(url);
Please move them via "Tab" or "Space" to achieve evenness

2023-07-28 19:48 UTC, NikitaGavruk commented on UI/WebDriver/Browser.cs
> +            GetDriver().Manage().Window.Maximize();
Let's create variable for GetDriver() and call it via it.

2023-07-31 06:12 UTC, NikitaGavruk approved these changes

2023-07-31 06:12 UTC, merged